In [4]:
import pandas as pd

df_kan_neat_summary = pd.read_json("results/all_test_results_summary.json")
# select columns: function_name, seed, train_rmse, test_rmse, num_generations
df_kan_neat_summary = df_kan_neat_summary[["function_name", "seed", "train_rmse", "test_rmse"]]
df_kan_neat_summary

   function_name  seed  train_rmse  test_rmse
0         ellipj    42    0.071654   0.072501
1         ellipj   123    0.088562   0.092546
2         ellipj  1000    0.055223   0.053688
3         ellipj   789    0.084836   0.087586
4         ellipj   456    0.068518   0.067864
5             jv    42    0.921593   0.964742
6             jv   123    0.868300   0.939373
7             jv  1000    0.916552   0.897875
8             jv   789    0.906753   0.929766
9             jv   456    0.912102   0.965028
10        lpmv_1    42    0.950367   0.930297
11        lpmv_1   123    0.960445   0.964786
12        lpmv_1  1000    0.930885   0.914768
13        lpmv_1   789    0.964616   1.000101
14        lpmv_1   456    0.964697   0.959409

In [16]:
# rename function_name to function
df_kan_neat_summary.rename(columns={"function_name": "function"}, inplace=True)

In [17]:
df_all_results = pd.read_csv("special_functions_results/experiment_results.csv")
df_all_results

,function,method,seed,num_generations,n_samples,pykan_width,pykan_steps_per_grid,status,train_loss,test_loss,parameters,runtime,best_fitness,log_file,results_file
0,ellipj,pykan,42,50,1000,"[[2, 0], [3, 0], [2, 0], [1, 0], [1, 0]]",10.0,completed,0.758970,0.754178,885.0,63.448180,NaN,NaN,NaN
1,ellipj,pykan,123,50,1000,"[[2, 0], [3, 0], [2, 0], [1, 0], [1, 0]]",10.0,completed,0.093414,0.157358,885.0,58.768534,NaN,NaN,NaN
2,ellipj,pykan,456,50,1000,"[[2, 0], [3, 0], [2, 0], [1, 0], [1, 0]]",10.0,completed,0.747818,0.741288,885.0,56.734756,NaN,NaN,NaN
3,ellipj,pykan,789,50,1000,"[[2, 0], [3, 0], [2, 0], [1, 0], [1, 0]]",10.0,completed,0.779749,0.784107,885.0,57.318369,NaN,NaN,NaN
4,ellipj,pykan,1000,50,1000,"[[2, 0], [3, 0], [2, 0], [1, 0], [1, 0]]",10.0,completed,0.759476,0.755058,885.0,60.169453,NaN,NaN,NaN
5,ellipj,kan-neat,42,50,1000,NaN,NaN,completed,NaN,NaN,NaN,2311.749636,0.071654,special_functions_results\kan-ellipj-seed42\lo...,special_functions_results\kan-ellipj-seed42\re...
6,ellipj,kan-neat,123,50,1000,NaN,NaN,completed,NaN,NaN,NaN,2952.680797,0.088562,special_functions_results\kan-ellipj-seed123\l...,special_functions_results\kan-ellipj-seed123\r...
7,ellipj,kan-neat,456,50,1000,NaN,NaN,completed,NaN,NaN,NaN,3106.765835,0.068518,special_functions_results\kan-ellipj-seed456\l...,special_functions_results\kan-ellipj-seed456\r...
8,ellipj,kan-neat,789,50,1000,NaN,NaN,completed,NaN,NaN,NaN,2491.837381,0.084836,special_functions_results\kan-ellipj-seed789\l...,special_functions_results\kan-ellipj-seed789\r...
9,ellipj,kan-neat,1000,50,1000,NaN,NaN,completed,NaN,NaN,NaN,2598.940145,0.055223,special_functions_results\kan-ellipj-seed1000\...,special_functions_results\kan-ellipj-seed1000\...
10,jv,pykan,42,50,1000,"[[2, 0], [3, 0], [1, 0], [1, 0], [1, 0]]",10.0,completed,0.268559,0.281858,649.0,51.259640,NaN,NaN,NaN
11,jv,pykan,123,50,1000,"[[2, 0], [3, 0], [1, 0], [1, 0], [1, 0]]",10.0,completed,0.261602,0.262316,649.0,44.142361,NaN,NaN,NaN
12,jv,pykan,456,50,1000,"[[2, 0], [3, 0], [1, 0], [1, 0], [1, 0]]",10.0,failed,NaN,NaN,NaN,21.457317,NaN,NaN,NaN
13,jv,pykan,789,50,1000,"[[2, 0], [3, 0], [1, 0], [1, 0], [1, 0]]",10.0,completed,0.260881,0.275574,649.0,48.932766,NaN,NaN,NaN
14,jv,pykan,1000,50,1000,"[[2, 0], [3, 0], [1, 0], [1, 0], [1, 0]]",10.0,completed,0.267412,0.258527,649.0,46.295006,NaN,NaN,NaN
15,jv,kan-neat,42,50,1000,NaN,NaN,completed,NaN,NaN,NaN,2593.778390,0.921593,special_functions_results\kan-jv-seed42\log_42...,special_functions_results\kan-jv-seed42\result...
16,jv,kan-neat,123,50,1000,NaN,NaN,completed,NaN,NaN,NaN,2349.702183,0.868300,special_functions_results\kan-jv-seed123\log_1...,special_functions_results\kan-jv-seed123\resul...
17,jv,kan-neat,456,50,1000,NaN,NaN,completed,NaN,NaN,NaN,2802.881835,0.912102,special_functions_results\kan-jv-seed456\log_4...,special_functions_results\kan-jv-seed456\resul...
18,jv,kan-neat,789,50,1000,NaN,NaN,completed,NaN,NaN,NaN,1674.881971,0.906753,special_functions_results\kan-jv-seed789\log_7...,special_functions_results\kan-jv-seed789\resul...
19,jv,kan-neat,1000,50,1000,NaN,NaN,completed,NaN,NaN,NaN,2420.010035,0.916552,special_functions_results\kan-jv-seed1000\log_...,special_functions_results\kan-jv-seed1000\resu...
20,lpmv_1,pykan,42,50,1000,"[[2, 0], [4, 0], [1, 0]]",10.0,completed,0.445414,1.232240,708.0,33.157376,NaN,NaN,NaN
21,lpmv_1,pykan,123,50,1000,"[[2, 0], [4, 0], [1, 0]]",10.0,completed,0.961278,1.059753,708.0,34.995558,NaN,NaN,NaN
22,lpmv_1,pykan,456,50,1000,"[[2, 0], [4, 0], [1, 0]]",10.0,completed,0.781042,1.375061,708.0,35.289889,NaN,NaN,NaN
23,lpmv_1,pykan,789,50,1000,"[[2, 0], [4, 0], [1, 0]]",10.0,completed,0.752858,1.042579,708.0,35.837339,NaN,NaN,NaN
24,lpmv_1,pykan,1000,50,1000,"[[2, 0], [4, 0], [1, 0]]",10.0,completed,0.374815,0.740031,708.0,33.497039,NaN,NaN,NaN
25,lpmv_1,kan-neat,42,50,1000,NaN,NaN,completed,NaN,NaN,NaN,2639.280020,0.950367,special_functions_results\kan-lpmv_1-seed42\lo...,special_functions_results\kan-lpmv_1-seed42\re...
26,lpmv_1,kan-neat,123,50,1000,NaN,NaN,completed,NaN,NaN,NaN,2505.177638,0.960445,special_functions_results\kan-lpmv_1-seed123\l...,special_functions_results\kan-lpmv_1-seed123\r...
27,lpmv_1,kan-neat,456,50,1000,NaN,NaN,completed,NaN,NaN,NaN,2514.234657,0.964697,special_functions_results\kan-lpmv_1-seed456\l...,special_functions_results\kan-lpmv_1-seed456\r...
28,lpmv_1,kan-neat,789,50,1000,NaN,NaN,completed,NaN,NaN,NaN,2506.311565,0.964616,special_functions_results\kan-lpmv_1-seed789\l...,special_functions_results\kan-lpmv_1-seed789\r...
29,lpmv_1,kan-neat,1000,50,1000,NaN,NaN,completed,NaN,NaN,NaN,3266.635615,0.930885,special_functions_results\kan-lpmv_1-seed1000\...,special_functions_results\kan-lpmv_1-seed1000\...

In [19]:
# rename train_loss and test_loss to train_rmse and test_rmse
df_all_results.rename(columns={"train_loss": "train_rmse", "test_loss": "test_rmse"}, inplace=True)

In [21]:
# Merge the relevant part of df_all_results with df_kan_neat_summary
mask = df_all_results["method"] == "kan-neat"
df_to_update = df_all_results[mask].merge(
    df_kan_neat_summary[["seed", "function", "train_rmse", "test_rmse"]],
    on=["seed", "function"],
    how="left",
    suffixes=("", "_new")
)

# Update values in df_all_results where applicable
df_all_results.loc[mask, "train_rmse"] = df_to_update["train_rmse_new"].values
df_all_results.loc[mask, "test_rmse"] = df_to_update["test_rmse_new"].values

In [22]:
df_all_results

,function,method,seed,num_generations,n_samples,pykan_width,pykan_steps_per_grid,status,train_rmse,test_rmse,parameters,runtime,best_fitness,log_file,results_file
0,ellipj,pykan,42,50,1000,"[[2, 0], [3, 0], [2, 0], [1, 0], [1, 0]]",10.0,completed,0.758970,0.754178,885.0,63.448180,NaN,NaN,NaN
1,ellipj,pykan,123,50,1000,"[[2, 0], [3, 0], [2, 0], [1, 0], [1, 0]]",10.0,completed,0.093414,0.157358,885.0,58.768534,NaN,NaN,NaN
2,ellipj,pykan,456,50,1000,"[[2, 0], [3, 0], [2, 0], [1, 0], [1, 0]]",10.0,completed,0.747818,0.741288,885.0,56.734756,NaN,NaN,NaN
3,ellipj,pykan,789,50,1000,"[[2, 0], [3, 0], [2, 0], [1, 0], [1, 0]]",10.0,completed,0.779749,0.784107,885.0,57.318369,NaN,NaN,NaN
4,ellipj,pykan,1000,50,1000,"[[2, 0], [3, 0], [2, 0], [1, 0], [1, 0]]",10.0,completed,0.759476,0.755058,885.0,60.169453,NaN,NaN,NaN
5,ellipj,kan-neat,42,50,1000,NaN,NaN,completed,0.071654,0.072501,NaN,2311.749636,0.071654,special_functions_results\kan-ellipj-seed42\lo...,special_functions_results\kan-ellipj-seed42\re...
6,ellipj,kan-neat,123,50,1000,NaN,NaN,completed,0.088562,0.092546,NaN,2952.680797,0.088562,special_functions_results\kan-ellipj-seed123\l...,special_functions_results\kan-ellipj-seed123\r...
7,ellipj,kan-neat,456,50,1000,NaN,NaN,completed,0.068518,0.067864,NaN,3106.765835,0.068518,special_functions_results\kan-ellipj-seed456\l...,special_functions_results\kan-ellipj-seed456\r...
8,ellipj,kan-neat,789,50,1000,NaN,NaN,completed,0.084836,0.087586,NaN,2491.837381,0.084836,special_functions_results\kan-ellipj-seed789\l...,special_functions_results\kan-ellipj-seed789\r...
9,ellipj,kan-neat,1000,50,1000,NaN,NaN,completed,0.055223,0.053688,NaN,2598.940145,0.055223,special_functions_results\kan-ellipj-seed1000\...,special_functions_results\kan-ellipj-seed1000\...
10,jv,pykan,42,50,1000,"[[2, 0], [3, 0], [1, 0], [1, 0], [1, 0]]",10.0,completed,0.268559,0.281858,649.0,51.259640,NaN,NaN,NaN
11,jv,pykan,123,50,1000,"[[2, 0], [3, 0], [1, 0], [1, 0], [1, 0]]",10.0,completed,0.261602,0.262316,649.0,44.142361,NaN,NaN,NaN
12,jv,pykan,456,50,1000,"[[2, 0], [3, 0], [1, 0], [1, 0], [1, 0]]",10.0,failed,NaN,NaN,NaN,21.457317,NaN,NaN,NaN
13,jv,pykan,789,50,1000,"[[2, 0], [3, 0], [1, 0], [1, 0], [1, 0]]",10.0,completed,0.260881,0.275574,649.0,48.932766,NaN,NaN,NaN
14,jv,pykan,1000,50,1000,"[[2, 0], [3, 0], [1, 0], [1, 0], [1, 0]]",10.0,completed,0.267412,0.258527,649.0,46.295006,NaN,NaN,NaN
15,jv,kan-neat,42,50,1000,NaN,NaN,completed,0.921593,0.964742,NaN,2593.778390,0.921593,special_functions_results\kan-jv-seed42\log_42...,special_functions_results\kan-jv-seed42\result...
16,jv,kan-neat,123,50,1000,NaN,NaN,completed,0.868300,0.939373,NaN,2349.702183,0.868300,special_functions_results\kan-jv-seed123\log_1...,special_functions_results\kan-jv-seed123\resul...
17,jv,kan-neat,456,50,1000,NaN,NaN,completed,0.912102,0.965028,NaN,2802.881835,0.912102,special_functions_results\kan-jv-seed456\log_4...,special_functions_results\kan-jv-seed456\resul...
18,jv,kan-neat,789,50,1000,NaN,NaN,completed,0.906753,0.929766,NaN,1674.881971,0.906753,special_functions_results\kan-jv-seed789\log_7...,special_functions_results\kan-jv-seed789\resul...
19,jv,kan-neat,1000,50,1000,NaN,NaN,completed,0.916552,0.897875,NaN,2420.010035,0.916552,special_functions_results\kan-jv-seed1000\log_...,special_functions_results\kan-jv-seed1000\resu...
20,lpmv_1,pykan,42,50,1000,"[[2, 0], [4, 0], [1, 0]]",10.0,completed,0.445414,1.232240,708.0,33.157376,NaN,NaN,NaN
21,lpmv_1,pykan,123,50,1000,"[[2, 0], [4, 0], [1, 0]]",10.0,completed,0.961278,1.059753,708.0,34.995558,NaN,NaN,NaN
22,lpmv_1,pykan,456,50,1000,"[[2, 0], [4, 0], [1, 0]]",10.0,completed,0.781042,1.375061,708.0,35.289889,NaN,NaN,NaN
23,lpmv_1,pykan,789,50,1000,"[[2, 0], [4, 0], [1, 0]]",10.0,completed,0.752858,1.042579,708.0,35.837339,NaN,NaN,NaN
24,lpmv_1,pykan,1000,50,1000,"[[2, 0], [4, 0], [1, 0]]",10.0,completed,0.374815,0.740031,708.0,33.497039,NaN,NaN,NaN
25,lpmv_1,kan-neat,42,50,1000,NaN,NaN,completed,0.950367,0.930297,NaN,2639.280020,0.950367,special_functions_results\kan-lpmv_1-seed42\lo...,special_functions_results\kan-lpmv_1-seed42\re...
26,lpmv_1,kan-neat,123,50,1000,NaN,NaN,completed,0.960445,0.964786,NaN,2505.177638,0.960445,special_functions_results\kan-lpmv_1-seed123\l...,special_functions_results\kan-lpmv_1-seed123\r...
27,lpmv_1,kan-neat,456,50,1000,NaN,NaN,completed,0.964697,0.959409,NaN,2514.234657,0.964697,special_functions_results\kan-lpmv_1-seed456\l...,special_functions_results\kan-lpmv_1-seed456\r...
28,lpmv_1,kan-neat,789,50,1000,NaN,NaN,completed,0.964616,1.000101,NaN,2506.311565,0.964616,special_functions_results\kan-lpmv_1-seed789\l...,special_functions_results\kan-lpmv_1-seed789\r...
29,lpmv_1,kan-neat,1000,50,1000,NaN,NaN,completed,0.930885,0.914768,NaN,3266.635615,0.930885,special_functions_results\kan-lpmv_1-seed1000\...,special_functions_results\kan-lpmv_1-seed1000\...

In [23]:
# select function, method, train_rmse, test_rmse, seed
df_all_results_selected = df_all_results[["function", "method", "train_rmse", "test_rmse", "seed"]]
df_all_results_selected

   function    method  train_rmse  test_rmse  seed
0    ellipj     pykan    0.758970   0.754178    42
1    ellipj     pykan    0.093414   0.157358   123
2    ellipj     pykan    0.747818   0.741288   456
3    ellipj     pykan    0.779749   0.784107   789
4    ellipj     pykan    0.759476   0.755058  1000
5    ellipj  kan-neat    0.071654   0.072501    42
6    ellipj  kan-neat    0.088562   0.092546   123
7    ellipj  kan-neat    0.068518   0.067864   456
8    ellipj  kan-neat    0.084836   0.087586   789
9    ellipj  kan-neat    0.055223   0.053688  1000
10       jv     pykan    0.268559   0.281858    42
11       jv     pykan    0.261602   0.262316   123
12       jv     pykan         NaN        NaN   456
13       jv     pykan    0.260881   0.275574   789
14       jv     pykan    0.267412   0.258527  1000
15       jv  kan-neat    0.921593   0.964742    42
16       jv  kan-neat    0.868300   0.939373   123
17       jv  kan-neat    0.912102   0.965028   456
18       jv  kan-neat    0.906753   0.929766   789
19       jv  kan-neat    0.916552   0.897875  1000
20   lpmv_1     pykan    0.445414   1.232240    42
21   lpmv_1     pykan    0.961278   1.059753   123
22   lpmv_1     pykan    0.781042   1.375061   456
23   lpmv_1     pykan    0.752858   1.042579   789
24   lpmv_1     pykan    0.374815   0.740031  1000
25   lpmv_1  kan-neat    0.950367   0.930297    42
26   lpmv_1  kan-neat    0.960445   0.964786   123
27   lpmv_1  kan-neat    0.964697   0.959409   456
28   lpmv_1  kan-neat    0.964616   1.000101   789
29   lpmv_1  kan-neat    0.930885   0.914768  1000

In [24]:
# Select best combinations grouped by function and method based on test_rmse
df_best_results = df_all_results_selected.loc[df_all_results_selected.groupby(["function", "method"])["test_rmse"].idxmin()]
df_best_results

   function    method  train_rmse  test_rmse  seed
9    ellipj  kan-neat    0.055223   0.053688  1000
1    ellipj     pykan    0.093414   0.157358   123
19       jv  kan-neat    0.916552   0.897875  1000
14       jv     pykan    0.267412   0.258527  1000
29   lpmv_1  kan-neat    0.930885   0.914768  1000
24   lpmv_1     pykan    0.374815   0.740031  1000

In [25]:
# save best results to a new CSV file
df_best_results.to_csv("best_results_per_function_method.csv", index=False)